export const METROS: Record<string, string> = {
    '300': `Tijuana, BA - San Diego, CA`,
    '301': `Ensenada, BA`,
    '302': `Rosarito, BA`,
    '303': `Mexicali, BA - Yuma, AZ - El Centro, CA`,
    '305': `La Paz - Consititucion - San Jose Del Cabo, BJ`,
    '310': `Agua Prieta, SO - Nogales, AZ/SO`,
    '311': `Hermosillo, SO`,
    '315': `Chihuaua, CH`,
    '316': `Ciudad Juarez, CH - El Paso, TX`,
    '320': `Piedras Negras - Ciudad Acuna, CU - Del Rio - Eagle, TX`,
    '321': `Zacatecas - Sombrete, ZA`,
    '322': `Aguascalientes - Calvillo -Ojocaliente, AG`,
    '325': `Nuevo Laredo, TA - Laredo, TX`,
    '326': `Matamoros, TA - Brownsville- Rio Grande Delta, TX`,
    '327': `San Luis Potosi - Tamazuncahle - Ciudad Valles, SL`,
    '330': `Monterrey, NN`,
    '335': `Oaxaca, OA`,
    '340': `Durango, DO`,
    '345': `Mazatlan, SI`,
    '347': `Tepic, NA`,
    '350': `Ciudad Victoria, TA`,
    '351': `Tampico, TA`,
    '360': `Poza Rica, VC`,
    '364': `Tlaxcala, TL`,
    '365': `Guadalajara, JL`,
    '366': `Puerto Vallarta, JL`,
    '367': `Guanajuato - Leon - Celaya, GX`,
    '368': `Queretaro , QU`,
    '369': `Tulancingo - Pachuca, HL`,
    '370': `Mexico City, DF`,
    '371': `Toluca - Altzomoni, MX`,
    '372': `Morelia - Zamora, MC`,
    '373': `Colima - Manzanillo - Tecoman, CL`,
    '374': `Puebla - Tehuacan, PB`,
    '375': `Veracruz, VC`,
    '376': `Oaxaca - Puerta Escondido, OA`,
    '377': `Tapachula, CI`,
    '378': `Villahermosa - La Venta, TB`,
    '379': `Campeche - Ciudad Del Carmen - Escarcega, CE`,
    '380': `Merida, YU`,
    '384': `Cuernavaca, MR`,
    '385': `Cancun, QR`,
    '386': `Acapulco, GR`,
    '490': `Puerto Rico`,
    '491': `Virgin Islands`,
    '493': `American Samoa`,
    '494': `Federated States OF Micronesia`,
    '495': `Guam`,
    '496': `Marshall Islands`,
    '497': `Minor Outlying Islands`,
    '498': `Northern Mariana Islands`,
    '499': `Palau`,
    '500': `Portland-Auburn`,
    '501': `New York`,
    '502': `Binghamton`,
    '503': `Macon`,
    '504': `Philadelphia`,
    '505': `Detroit`,
    '506': `Boston-Manchester`,
    '507': `Savannah`,
    '508': `Pittsburgh`,
    '509': `Ft. Wayne`,
    '510': `Cleveland-Akron-Canton`,
    '511': `Washington, DC-Hagarstown`,
    '512': `Baltimore`,
    '513': `Flint-Saginaw-Bay City`,
    '514': `Buffalo`,
    '515': `Cincinnati`,
    '516': `Erie`,
    '517': `Charlotte`,
    '518': `Greensboro-High Point-Winston/Salem`,
    '519': `Charleston, SC`,
    '520': `Augusta`,
    '521': `Providence-New Bedford`,
    '522': `Columbus, GA-Opelika, AL`,
    '523': `Burlington-Plattsburgh`,
    '524': `Atlanta`,
    '525': `Albany, GA`,
    '526': `Utica`,
    '527': `Indianapolis`,
    '528': `Miami-Ft. Lauderdale`,
    '529': `Louisville`,
    '530': `Tallahassee-Thomasville`,
    '531': `Tri-Cities, TN-VA`,
    '532': `Albany-Schenectady-Troy`,
    '533': `Hartford-New Haven`,
    '534': `Orlando-Daytona Beach-Melbourne`,
    '535': `Columbus, OH`,
    '536': `Youngstown`,
    '537': `Bangor`,
    '538': `Rochester, NY`,
    '539': `Tampa-St. Petersburg-Sarasota`,
    '540': `Traverse City-Cadillac`,
    '541': `Lexington`,
    '542': `Dayton`,
    '543': `Springfield-Holyoke`,
    '544': `Norfolk-Portsmith-Newport News`,
    '545': `Greenville-New Bern-Washington,NC`,
    '546': `Columbia, SC`,
    '547': `Toledo`,
    '548': `West Palm Beach-Ft. Pierce`,
    '549': `Watertown`,
    '550': `Wilmington`,
    '551': `Lansing`,
    '552': `Presque Isle`,
    '553': `Marquette`,
    '554': `Wheeling-Steubenville`,
    '555': `Syracuse`,
    '556': `Richmond-Petersburg`,
    '557': `Knoxville`,
    '558': `Lima`,
    '559': `Bluefield-Beckley-Oak Hill`,
    '560': `Raleigh-Durham-Fayettevlle`,
    '561': `Jacksonville`,
    '563': `Grand Rapids-Kalamazoo-Battlecreek`,
    '564': `Charleston-Huntington`,
    '565': `Elmira-Corning`,
    '566': `Harrisburg-Lancaster-Lebanon-York,PA`,
    '567': `Greenville-Sparta-Asheville`,
    '569': `Harrisonburg`,
    '570': `Myrtle Beach-Florence`,
    '571': `Ft. Myers-Naples`,
    '573': `Roanoke-Lynchburg`,
    '574': `Johnstown-Altoona-ST Colge`,
    '575': `Chattanooga`,
    '576': `Salisbury`,
    '577': `Wilkes Barre-Scranton`,
    '581': `Terre Haute`,
    '582': `Lafayette, IN`,
    '583': `Alpena`,
    '584': `Charlottesville`,
    '588': `South Bend-Elkhart`,
    '592': `Gainesville`,
    '596': `Zanesville`,
    '597': `Parkersburg`,
    '598': `Clarksburg-Weston`,
    '600': `Corpus Christi`,
    '602': `Chicago`,
    '603': `Joplin-Pittsburg`,
    '604': `Columbia-Jefferson City`,
    '605': `Topeka`,
    '606': `Dothan`,
    '609': `St. Louis`,
    '610': `Rockford`,
    '611': `Rochestr-Mason City-Austin`,
    '612': `Shreveport`,
    '613': `Minneapolis-St. Paul`,
    '616': `Kansas City`,
    '617': `Milwaukee`,
    '618': `Houston`,
    '619': `Springfield, MO`,
    '622': `New Orleans`,
    '623': `Dallas-Ft. Worth`,
    '624': `Sioux City`,
    '625': `Waco-Temple-Bryan`,
    '626': `Victoria`,
    '627': `Wichita Falls & Lawton`,
    '628': `Monroe-El Dorado`,
    '630': `Birmingham-Anniston-Tuscaloosa`,
    '631': `Ottumwa-Kirksville`,
    '632': `Paducah-Cape Girardo-Harrisburg`,
    '633': `Odessa-Midland`,
    '634': `Amarillo`,
    '635': `Austin`,
    '636': `Harlingen-Weslaco-Brownsville-Mcarthur`,
    '637': `Cedar Rapids-Waterloo-Iowa City & Dubuque, IA`,
    '638': `St. Joseph`,
    '639': `Jackson, TN`,
    '640': `Memphis`,
    '641': `San Antonio`,
    '642': `Lafayette, LA`,
    '643': `Lake Charles`,
    '644': `Alexandria, LA`,
    '647': `Greenwood-Greenville`,
    '648': `Champaign & Springfield-Decatur`,
    '649': `Evansville`,
    '650': `Oklahoma City`,
    '651': `Lubbock`,
    '652': `Omaha`,
    '656': `Panama City`,
    '657': `Sherman-Ada`,
    '658': `Green Bay-Appleton`,
    '659': `Nashville`,
    '661': `San Angelo`,
    '662': `Abilene-Sweetwater`,
    '669': `Madison`,
    '670': `Ft. Smith-Fayetteville-Sprngdale-Rogers`,
    '671': `Tulsa`,
    '673': `Columbus-Tupelo-West Point`,
    '675': `Peoria-Bloomington`,
    '676': `Duluth-Superior`,
    '678': `Wichita-Hutchinson Plus`,
    '679': `Des Moines-Ames`,
    '682': `Davenport-R.Island-Moline`,
    '686': `Mobile-Pensacola`,
    '687': `Minot-Bismarck-Dickinson`,
    '691': `Huntsville-Decatur-Florence`,
    '692': `Beaumont-Port Arthur`,
    '693': `Little Rock-Pine Bluff`,
    '698': `Montgomery-Selma`,
    '702': `La Crosse-Eau Claire`,
    '705': `Wausau-Rhinelander`,
    '709': `Tyler-Longview (Lufkin&Nacogdoches)`,
    '710': `Hattiesburg-Laurel`,
    '711': `Meridian`,
    '716': `Baton Rouge`,
    '717': `Quincy-Hannibal-Keokuk`,
    '718': `Jackson, MS`,
    '722': `Lincoln & Hastings-Kearny`,
    '724': `Fargo-Valley City`,
    '725': `Sioux Falls-Mitchell`,
    '734': `Jonesboro`,
    '736': `Bowling Green`,
    '737': `Mankato`,
    '740': `North Platte`,
    '743': `Anchorage`,
    '744': `Honolulu`,
    '745': `Fairbanks`,
    '746': `Biloxi-Gulfport`,
    '747': `Juneau`,
    '749': `Laredo`,
    '751': `Denver`,
    '752': `Colorado Springs-Pueblo`,
    '753': `Phoenix-Prescott`,
    '754': `Butte-Bozeman`,
    '755': `Great Falls`,
    '756': `Billings`,
    '757': `Boise`,
    '758': `Idaho Falls-Pocatello-Jackson`,
    '759': `Cheyenne-Scottsbluff`,
    '760': `Twin Falls`,
    '762': `Missoula`,
    '764': `Rapid City`,
    '765': `El Paso-Las Cruces`,
    '766': `Helena`,
    '767': `Casper-Riverton`,
    '770': `Salt Lake City`,
    '771': `Yuma-El Centro`,
    '773': `Grand Junction-Montrose`,
    '789': `Tucson-Sierra Vista`,
    '790': `Albuquerque-Santa FE`,
    '798': `Glendive`,
    '800': `Bakersfield`,
    '801': `Eugene`,
    '802': `Eureka`,
    '803': `Los Angeles`,
    '804': `Palm Springs`,
    '807': `San Francisco-Oakland-San Jose`,
    '810': `Yakima-Pasco-Richland-Kennwick`,
    '811': `Reno`,
    '813': `Medford-Klamath Falls`,
    '819': `Seattle-Tacoma`,
    '820': `Portland, OR`,
    '821': `Bend, OR`,
    '825': `San Diego`,
    '828': `Monterey-Salinas`,
    '839': `Las Vegas`,
    '855': `Santa Barbara-Santa Maria-San Luis Obispo`,
    '862': `Sacramento-Stockton-Modesto`,
    '866': `Fresno-Visalia`,
    '868': `Chico-Redding`,
    '881': `Spokane`,
    '900': `St. Johns - Corner Brook, NL`,
    '905': `Halifax - Dartmouth, NS`,
    '906': `Sydney - Glace Bay, NS`,
    '910': `Charlottetown, Pei`,
    '915': `Rimonouski - Matane - Sept Iles - Gaspe - Perce QC, Cambellton - Bathurst, NB`,
    '916': `St. John - Fredericton - Moncton, NB`,
    '920': `Chaleur Bay - Carleton, QC`,
    '921': `Montreal - Laval, QC`,
    '922': `Ottawa, ON - Gatineau, QC`,
    '923': `Quebec City - Levis, QC`,
    '924': `Riviere DU Loup, QC`,
    '925': `Rouyn - Noranda - Val D'OR, QC`,
    '926': `Saguenay, QC`,
    '927': `Sherbrooke, QC`,
    '928': `Trois -Rivieres - Shawinigan, QC`,
    '940': `Barrie - Orillia, ON`,
    '941': `Kenora, ON`,
    '942': `Kingston, ON`,
    '943': `Kitchener - Waterloo - Cambridge - Guelph, ON`,
    '944': `London - Woodstock - Wingham, ON`,
    '945': `Pembroke - Petawawa, ON`,
    '946': `Peterborough - Belleville - Trenton, ON`,
    '947': `Sault Sainte Marie, ON`,
    '948': `Sudbury - Timmins - North Bay, ON`,
    '949': `Thunder Bay, ON`,
    '950': `Toronto - Hamilton - Niagra Falls, ON`,
    '951': `Windsor, ON`,
    '960': `Winnipeg - Brandon, MB`,
    '965': `Prince Albert, SK`,
    '966': `Regina - Moose Jaw, SK`,
    '967': `Saskatoon, SK`,
    '968': `Swift Current, SK`,
    '969': `Yorkton, SK`,
    '972': `Calgary - Lethbridge, AB`,
    '973': `Edmonton, AB`,
    '974': `Lloydminster, AB/SK`,
    '975': `Medicine Hat, AB`,
    '976': `Red Deer, AB`,
    '980': `Dawson Creek, BC`,
    '981': `Kelowna - Okanagan Valley - Kamloops, BC`,
    '982': `Prince George, BC`,
    '983': `Terrace - Kitimat - Prince Rupert, BC`,
    '984': `Vancouver - Victoria, BC`,
    '990': `Iqaluit, NU`,
    '993': `Yellowknife, NT`,
    '996': `Whitehorse, YT`,
};
